---

- hosts: web
  gather_facts: yes
  become: true
  tasks:
  - name: Change nginx reverse proxy
    copy:
      src: /etc/ansible/devops_eng114/default
      dest: /etc/nginx/sites-available/default

  - name: restart nginx
    service: name=nginx state=restarted enabled=yes