# test-svc.yml
- hosts: aws_db
  become: yes
  gather_facts: yes
  tasks:
  - name: "Populate service facts"
    service_facts:
  - name: "Check the service mongodb facts as they are"
    debug:
      msg: "{{ansible_facts.services['mongodb-org.service'].state}}"
  - name: "Verify if mongo is running!"
    assert:
      that:
        - "'{{ansible_facts.services['mongodb-org.service'].state}}' == 'running'"
      fail_msg: "mongodb is down, please check nginx status or restart!"
      success_msg: "no issues, service is running as expected"